### ISSUE TITLE
Python 3 StringIO import not valid

### ISSUE THREAD

**Issue by MattParr** [MattParr/python-atws#14]
```
(photo1)[matt@biglaptop python-atws]$ create_picklist_module
Suds version (0.6) not supported. Please use 0.7
Traceback (most recent call last):
  File "/home/matt/git/python-atws/atws/connection.py", line 26, in <module>
    import cStringIO as StringIO
ImportError: No module named 'cStringIO'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/matt/.virtualenvs/photo1/bin/create_picklist_module", line 9, in <module>
    load_entry_point('atws', 'console_scripts', 'create_picklist_module')()
  File "/home/matt/.virtualenvs/photo1/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/matt/.virtualenvs/photo1/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/home/matt/.virtualenvs/photo1/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/home/matt/.virtualenvs/photo1/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/matt/git/python-atws/atws/__init__.py", line 4, in <module>
    from .wrapper import connect
  File "/home/matt/git/python-atws/atws/wrapper.py", line 24, in <module>
    from . import connection
  File "/home/matt/git/python-atws/atws/connection.py", line 28, in <module>
    import StringIO
ImportError: No module named 'StringIO'
```

**Comment by MattParr** [comment]
44f7f36 fixed this
