### ISSUE TITLE
create_picklist_module raises exception : xml.sax._exceptions.SAXParseException: <unknown>:28:74: not well-formed (invalid token)

### ISSUE THREAD

**Issue by lc3t35** [MattParr/python-atws#16]
OSX 10.8.5 python 2.7.2

```
create_picklist_module --username 'xxxx@provectio.fr' --password 'xxxx' --url "https://webservices10.autotask.net/atservices/1.5/atws.wsdl" atvar.py
No handlers could be found for logger "atws.connection"
Traceback (most recent call last):
  File "/usr/local/bin/create_picklist_module", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/atws/create_picklist_module.py", line 32, in main
    create_atvar_module(at, entities, target_path)
  File "/Library/Python/2.7/site-packages/atws/helpers.py", line 323, in create_atvar_module
    field_info_response = get_field_info(at,entity_type)
  File "/Library/Python/2.7/site-packages/atws/helpers.py", line 283, in get_field_info
    return wrapper.GetFieldInfo(fields)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 621, in send
    original_soapenv=original_soapenv)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 661, in process_reply
    replyroot = _parse(reply)
  File "/Library/Python/2.7/site-packages/suds/client.py", line 832, in _parse
    return Parser().parse(string=string)
  File "/Library/Python/2.7/site-packages/suds/sax/parser.py", line 133, in parse
    sax.parse(source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 107, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/expatreader.py", line 211, in feed
    self._err_handler.fatalError(exc)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:28:74: not well-formed (invalid token)
```

**Comment by MattParr** [comment]
Okay thank you.  I can confirm the module is fine, if you don't specify a URL, or if you specify the right URL.  I can repeat the problem simply by using exactly what you have indicated above (I'm including the obscured email and password)

I'll have to catch this and raise something more helpful like a ZoneURLError or InvalidUserError.

**Comment by MattParr** [comment]
The Invalid Auth request throws the following error in HTML:

```
Server Error in '/ATServices' Application.
Unhandled Execution Error
Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code.

Exception Details: System.Web.Services.Protocols.SoapException:

Source Error:

An unhandled exception was generated during the execution of the current web request. Information regarding the origin and location of the exception can be identified using the exception stack trace below.

Stack Trace:


[SoapException]
   autotask.web.services.Global.Application_AuthenticateRequest(Object sender, EventArgs e) +1008
   System.Web.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +136
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +69


Version Information: Microsoft .NET Framework Version:4.0.30319; ASP.NET Version:4.0.30319.34280
```

**Comment by MattParr** [comment]
There isn't a way to handle this correctly.  The server side is at fault.
I may update the wrapper to test the supplied credentials should an error that looks like this occur.

To provide more information in an error message, the wrapper would have to make a query to GetZoneInfo.
If it succeeds, and the URL is correct, then I could make the assumption that the password is incorrect.
If it succeeds, and the URL is wrong, then client should probably throw a warning and then continue using the correct URL.
If it fails, I can't really say for sure that the problem is a credential issue.  But I could throw an UnhandledServerSideError which would at least be better than what we have got.

**Comment by lc3t35** [comment]
It works fine with the London Zone (webservices4 instead of 10) . I was able to output atvar.py.
