### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by LarryMartell** [MattParr/python-atws#42]
Python 2.7.6 on ubuntu-trusty-64 3.13.0-87-generic

```
>>> import atws
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/atws/__init__.py", line 4, in <module>
    from .wrapper import connect
  File "/usr/local/lib/python2.7/dist-packages/atws/wrapper.py", line 32, in <module>
    from . import connection
  File "/usr/local/lib/python2.7/dist-packages/atws/connection.py", line 19, in <module>
    from requests.exceptions import ConnectTimeout, Timeout, ReadTimeout, SSLError
ImportError: cannot import name ConnectTimeout
```

**Comment by LarryMartell** [comment]
I had an old version of requests, 2.2.1. I updated requests to 2.18.4 and it fixed that issue, but now when I import atws I get:

No handlers could be found for logger "atws.connection"

**Comment by MattParr** [comment]
It's just because atws makes logging calls, but you have not configured logging.
https://docs.python.org/2/howto/logging.html#configuring-logging-for-a-library

from the Requests code itself, we can find a suitable solution.  I'd accept a pull request to get rid of this message:
```python
# Set default logging handler to avoid "No handler found" warnings.
import logging
try:  # Python 2.7+
    from logging import NullHandler
except ImportError:
    class NullHandler(logging.Handler):
        def emit(self, record):
            pass

logging.getLogger(__name__).addHandler(NullHandler())
```
