### ISSUE TITLE
Error with atws.connect

### ISSUE THREAD

**Issue by dahifi** [MattParr/python-atws#59]
First time trying to use this module. 

Python 3.6.7
```
Suds version (0.6) not ideal. Please use 0.7
Traceback (most recent call last):
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/connection.py", line 192, in __init__
    self.client = kwargs['client']
KeyError: 'client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 28, column 74

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/el/cmitos/autotask_api.py", line 4, in <module>
    at = atws.connect(username='USERNAME', password='PASSWORD')
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/wrapper.py", line 47, in connect
    wrapper = connection.connect(atws_version=Wrapper,**kwargs)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/connection.py", line 108, in connect
    return obj(**kwargs)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/connection.py", line 195, in __init__
    self.client = suds.client.Client(**options)            
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/client.py", line 115, in __init__
    self.wsdl = reader.open(url)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/reader.py", line 150, in open
    d = self.fn(url, self.options)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/reader.py", line 74, in open
    d = self.download(url)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/reader.py", line 100, in download
    return sax.parse(string=content)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/sax/parser.py", line 133, in parse
    sax.parse(source)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.6/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:28:74: not well-formed (invalid token)

```

**Comment by hoerup** [comment]
Start with this one: "Suds version (0.6) not ideal. Please use 0.7"

**Comment by dahifi** [comment]
After installing suds2: 

```
Traceback (most recent call last):
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/connection.py", line 192, in __init__
    self.client = kwargs['client']
KeyError: 'client'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 217, in feed
    self._parser.Parse(data, isFinal)
xml.parsers.expat.ExpatError: not well-formed (invalid token): line 28, column 74
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-6aeb01f0d233>", line 1, in <module>
    at = atws.connect(username='autotaskAPI@cmit201213.com', password='hjk!1Fb014Mp')
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/wrapper.py", line 47, in connect
    wrapper = connection.connect(atws_version=Wrapper,**kwargs)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/connection.py", line 108, in connect
    return obj(**kwargs)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/atws/connection.py", line 195, in __init__
    self.client = suds.client.Client(**options)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/client.py", line 120, in __init__
    self.wsdl = reader.open(url)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/reader.py", line 104, in open
    wsdl = self.fn(url, self.options)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/wsdl.py", line 164, in __init__
    d = reader.open(url)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/reader.py", line 148, in open
    xml = self.__fetch(url)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/reader.py", line 196, in __fetch
    return sax.parse(string=content)
  File "/home/el/.local/share/virtualenvs/cmitos-VMCTcgIO/lib/python3.6/site-packages/suds/sax/parser.py", line 131, in parse
    sax.parse(source)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 111, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python3.6/xml/sax/xmlreader.py", line 125, in parse
    self.feed(buffer)
  File "/usr/lib/python3.6/xml/sax/expatreader.py", line 221, in feed
    self._err_handler.fatalError(exc)
  File "/usr/lib/python3.6/xml/sax/handler.py", line 38, in fatalError
    raise exception
xml.sax._exceptions.SAXParseException: <unknown>:28:74: not well-formed (invalid token)
```

I'm not entirely certain that I'm not seeing an auth error. These are the same credentials that we use for our PSA integration -- this is still the 1/5 API, so the token isn't required, correct?

**Comment by dahifi** [comment]
Disregard, looks like an auth error. Confirmed using alternate credentials. Thanks!
